name: blue_bird_cli
description: A powerful CLI tool to kickstart your Flutter projects with clean, scalable architectures that grow with your app.
version: 1.0.0
repository: https://github.com/Abel1027/blue-bird-cli

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  glob: ^2.1.3
  lcov_parser: ^0.1.2
  mason: ^0.1.2
  mason_logger: ^0.3.3
  meta: ^1.18.0
  path: ^1.9.1
  pub_updater: ^0.5.0
  pubspec_parse: ^1.4.0
  stack_trace: ^1.12.1
  universal_io: ^2.2.2
  very_good_test_runner: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.1
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ">=7.0.0 <11.0.0"

executables:
  blue_bird:
